#!/bin/bash
# Screenshot: http://s.natalian.org/2013-08-17/dwm_status.png
# Network speed stuff stolen from http://linuxclues.blogspot.sg/2009/11/shell-script-show-network-speed.html


print_date(){
	date "+%a %m-%d %T%:::z"
}


while true
do

	# Get new transmitted, received byte number values and current time

	# Calculates speeds
	xsetroot -name " $(print_date)"

	# Update old values to perform new calculations

	sleep 1

done
